### PR TITLE
Add introspection in controllers as @app instance variable

### PR DESCRIPTION
**Pull request by canadaduane**
I'd like to contribute to rumm, and my first thought was to create a more complete 'help' command. The best way I can think of to do this is to add introspective capabilities to mvcli so that we can check the routes in the controller, and via the routes describe what commands are available.

I'm making this pull request now so that you can review the changes and think about whether this makes sense for your project. I can add specs if you like the direction.

### CODE REVIEW

**Comment by cowboyd** [comment]
Hi Duane. I'm so glad that you're interested, and would love to have you contribute to rum. As it turns out, I'm working on this exact same problem (better help) and your instinct is correct, there needs to be some way for controllers to get ahold of the router. If you're interested we could team up on this.

While your PR solves this handily for the case of the controller, I'd like to solve this problem system wide. MVCLI uses a light-weight dependency resolution system called `MVCLI::Provisioning` that is used extensively by rumm. It is loosely based on JSR-311 providers and the idea is that any object anywhere says:

``` ruby
requires :foo
```

And it will at runtime have a `foo` method that holds a reference to the foo object. To find the `foo` object, the FooProvider is loaded and invoked to return the reference. Here is an example from rumm https://github.com/rackerlabs/rumm/blob/master/app/providers/compute_provider.rb

If feasible, I'd like for the the core runtime to dogfood the provisioning system, so that the router is instantiated with a RouterProvider and is then available to _any_ object that needs it without being coupled to "container" objects, or have object hold onto other objects merely so that they can pass them around.

**Comment by canadaduane** [comment]
So that's the magic sauce! I hadn't quite put together how these `requires` statements were calling code. My next question was going to be "but where's the CommandProvider"... but digging in to MVCLI shows that it's a special case.

So it seems to me like these *Providers are like globally accessible variables, called into existence within a class scope, with special autoloading so that their definition corresponds to the names of the files in which they are located. Is that about right?

Coming from Haskell I instinctively want to replace globals with function arguments, but there does seem to be a kind of elegance to the *Providers. In the case of a RouterProvider, I guess there is no need to have more than one Router. So putting it all together, I guess a global/singleton makes sense to me.

**Comment by cowboyd** [comment]
Ironically, the provider framework is an attempt at introducing FP principles into the runtime, so hopefully coming from Haskell you won't feel too dirty. 

Instead of thinking about them as shared global state, I think about them about it them as immutable pieces of your program that self-assemble based on the on the current execution context.  It might be a stretch, but you could think of it like the `import` statement in Haskell.

``` haskell
import Fog(compute)
```

except dynamic :) 

In other words, `Provider#value` should be a function with no side effects that given the same command will always yield the same value. That's why the command is the only a-priori knowledge in the system. Everything else must be derived using only it + other provided values.

Another option that would not require special casing would be to have `Provider#value` accept the command as its single argument.

To connect it back to the pull request, if there were a `RouterProvider`, then the `router` object would be a function of the command. However, in the future, we may want the RouterProvider to accept a --routes-file FILENAME parameter which would read routes from elsewhere in the system. The router would still be a pure function of the command, but could be completely different depending on the value of that option.

**Comment by cowboyd** [comment]
Also note that the provider namespace need not need be flat (though it currently is, as you noticed)

I think it makes a lot of sense to have them grouped by some sort of hand-wavy "namespace" that is associated with the current call stack, so if I'm doing a `servers` type thing and I say `requires :foo` then it will check for `app/providers/servers/foo_provider.rb` first before moving on to `app/providers/foo_provider.rb` and then finally checking in `mvcli/core/providers/foo_provider.rb` before finally giving up.

To always get the servers provider, you would perhaps say `requires "servers/foo"`

All that is highly speculative though.

**Comment by hayesmp** [comment]
!! Someone is still using this?

**Comment by canadaduane** [comment]
Haha, fwiw I am not using it; however! I recently discovered https://github.com/dlvhdr/gh-dash and it made it easy for me to discover old PRs and close them :)

**Comment by hayesmp** [comment]
Oh haha. Its was funny seeing this PR get closed after 10 years.

**Pull request closed without merging**
